name: photo_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  device_info_plus: ^9.0.0

  fluttertoast: ^8.2.1
  image: ^4.0.17
  image_picker: ^0.8.7+4
  image_cropper: ^3.0.3
  gallery_saver: ^2.3.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4

  tflite_flutter: ^0.9.5
  flutter_color_models: ^1.3.3+2
  flutter_colorpicker: ^1.0.3

  shared_preferences: ^2.1.0

  cupertino_icons: ^1.0.2
  scroll_loop_auto_scroll: ^0.0.5

  photofilters:
    path: photofilters

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/colorization_model_places365.tflite
    - assets/colorization_model_celebA.tflite
    - assets/colorization_model_flowers.tflite
    - assets/home_page_photos/places365_01.png
    - assets/home_page_photos/places365_02.png
    - assets/home_page_photos/celebA_01.png
    - assets/home_page_photos/celebA_02.png
    - assets/home_page_photos/flowers_01.png
    - assets/home_page_photos/flowers_02.png
    - assets/divider.png